# Basic Information 
title: Ahmad Mustafa, PhD
position: Machine Learning Researcher
affiliation: Georgia Institute of Technology 
affiliation_link: 
affiliation_logo: 
email: ahmadmustafa(dot)am(at)gmail.com

# Search Engine Optimization (SEO)
keywords: ahmad mustafa, mustafa ahmad, amustafa9
canonical: 
description: Ahmad Mustafa is a Researcher in Machine/Deep Learning. He holds PhD and Masters degrees in Electrical Engineering at the Georgia Institute of Technology.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=x10e8yQAAAAJ&hl=en
github_link: https://github.com/amustafa9
linkedin: https://www.linkedin.com/in/amustafa9/
researchgate: https://www.researchgate.net/profile/Ahmad-Mustafa-27

# Images 
avatar: ./assets/img/profile2.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnotes

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
