# Basic Information 
title: Ahmad Mustafa
position: Machine Learning and Analytics Engineer
affiliation: Occidental Petroleum
affiliation_link: 
affiliation_logo: 
email: ahmad_mustafa (at) oxy.com

# Search Engine Optimization (SEO)
keywords: ahmad mustafa, mustafa ahmad, amustafa9
canonical: 
description: Ahmad Mustafa is currently an ML Engineer at OXY based in Houston, TX. He holds PhD and Masters degrees in Electrical Engineering at the Georgia Institute of Technology.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=Uf9GqRsAAAAJ
cv_link: https://pages.jh.edu/yliu538/files/Yaoyao_Liu_Curriculum_Vitae.pdf
github_link: https://github.com/yaoyao-liu/
linkedin: https://www.linkedin.com/in/liuyaoyao/
twitter: https://twitter.com/YaoyaoLiu1/

# Images 
avatar: https://img.yliu.me/avatar.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
footnote: Feel free to use my website's source code.
footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: CJD8XwsJhSyQ6sbsU-Gw0cNcUlbah7KW3xvHN2QlwW0

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
